### ISSUE TITLE
dygraph not rendered in .tabset

### ISSUE THREAD

**Issue by fhirschmann** [rstudio/dygraphs#101]
Hello,

I noticed dygraphs are not shown in rmarkdown's HTML output when .tabset is used.

A minimal example looks as follows:

    ---
    output: html_document
    ---
    ```{r}
    library(DT)
    library(dygraphs)
    ```

    ## Tabs {.tabset}

    ### Tab 1

    ### Tab 2
    ```{r}
    dygraph(mdeaths)
    ```

It works fine when it is placed in Tab 1.

**Comment by jjallaire** [comment]
Thanks for reporting. Fixed via https://github.com/rstudio/dygraphs/commit/6ed9f961c7cafd414ae4b7c994f6e3b652d4884b
