### ISSUE TITLE
Number-based time instead of Date-based time

### ISSUE THREAD

**Issue by wamserma** [rstudio/dygraphs#103]
Hi,

I was looking into using dygraphs for visualising (simulated) measurement results (e.g. Voltage ~ Time). The timestamps are in nanoseconds relative to the beginning of the measurement. Converting to a POSIX time does not make much sense, as the actual Date/Time of the experiment is not relevant for the data.
`dygraphs` does support such kind of data (see "x-values" in view-source:http://dygraphs.com/data.html and the example at http://dygraphs.com/gallery/#g/highlighted-region).

However, this would require to be able to pass something a bit different from an `xts` object, such as a matrix that gets passed on into the native Array format of dygraphs.

**Comment by jjallaire** [comment]
We recently added support for standard numeric data in dygraphs, see:
https://github.com/rstudio/dygraphs/blob/master/R/dygraph.R#L6-L10

**Comment by wamserma** [comment]
My fault. I should have looked beyond https://rstudio.github.io/dygraphs/index.html (where only `xts` is mentioned).
