### ISSUE TITLE
FR: Modifying existing graphs with dygraphProxy

### ISSUE THREAD

**Issue by michelk** [rstudio/dygraphs#104]
In [Leaflet for R](https://rstudio.github.io/leaflet/shiny.html) it is possible to modify existing maps with a `proxy`. 

It would be great to have a similar feature in `dygraphs`, to modify an existing graph (e.g. draw a `dyEvent`)

**Comment by jjallaire** [comment]
It ends up being the case that dygrahps doesn't deal terrifically well with incremental updates (various bugs are tickled) so we use a full redraw. I don't see this changing given the issues we've observed in the  past with attempting incremental updates.
