### ISSUE TITLE
xAxisRange() for R

### ISSUE THREAD

**Issue by discoraj** [rstudio/dygraphs#105]
Is there anyway to get the x range for the current visible window?
So I can do some math on what is selected?

Like in the java script version but with real dates instead of the epoch version:
xAxisRange()
Returns the currently-visible x-range. This can be affected by zooming, panning or a call to updateOptions. Returns a two-element array: [left, right]. If the Dygraph has dates on the x-axis, these will be millis since epoch.

**Comment by jjallaire** [comment]
We make available Shiny inputs for the currently selected range. See
https://rstudio.github.io/dygraphs/shiny.html#shiny-date-input

**Comment by discoraj** [comment]
Thanks!! 
Perfect.
I can't believe I missed that.
