### ISSUE TITLE
FR: support for dyEvent with multiple events

### ISSUE THREAD

**Issue by michelk** [rstudio/dygraphs#107]
Currently if the are multiple events to plot, one has to use

    ...
    dyEvent("1950-6-30", "Korea", labelLoc = "bottom") %>%
    dyEvent("1965-2-09", "Vietnam", labelLoc = "bottom")

But this is not handy if there are multiple events and the number of events is not predictable in advance. 

Then is would be much more comfortable to write

    ...
    dyEvent(c("1950-6-30","1965-2-09"), c("Korea","Vietnam"), labelLoc = "bottom")

**Comment by discoraj** [comment]
Very similar to what I was thinking for the shading

**Comment by jjallaire** [comment]
Would welcome a PR to do this for shading as well.

**Comment by michelk** [comment]
Fixed with 9bcabe75e064dc89fadce5a30e1c382a24fb4f36
