### ISSUE TITLE
Issues in DateTime variable

### ISSUE THREAD

**Issue by khannasiddharth** [rstudio/dygraphs#119]
Hello All,

I have a Datetime variable in the form - 5/23/2015 13:31 (mm/dd/yyy hh:mm format) in a dataframe 'df'.
I want to extract Hour , Weekday ,Month & Year and using -

Hour = hour(df$DateTime, format = "%h")
Weekday = wday(df$DateTime)
Month = month(df$DateTime, "%m") 
Year = year(df$DateTime)

But I get error -
Error in as.POSIXlt.character(x, tz = tz(x)) : 
  character string is not in a standard unambiguous format

For all 4 conversions. Kindly help how I can resolve error.

KR
SK

**Comment by klaukh** [comment]
Unless this can be shown as a problem with the dygraphs package, I recommend this issue be closed.
