### ISSUE TITLE
Multiple Dygraphs Fail to Render in Flexdashboard

### ISSUE THREAD

**Issue by mark-fastpay** [rstudio/dygraphs#121]
I am having a regression with issue between dygraphs 0.9 and released version dygraphs 1.1.  Upon upgrading the library, a flexdashboard that hosts multiple dygraphs will only render one at a time (a different one for each update, so it seems as though this might be a race condition), the rest of them failing to appear.  The error presented is: TypeError: null is not an object (evaluating 'dygraph.xAxisRange') on the two graphs of three that fail to render.

**Comment by jjallaire** [comment]
I need a minimum reproducible example in order to investigate further.

**Comment by mark-fastpay** [comment]
I am attaching a zip file containing an Rmarkdown flexdashboard with 3 dygraphs.  Only one will successfully render (and the one that succeeds is not consistent, making me think this may be a race condition of some sort).  Similar issues seem to be reported upstream with shinydashboard on the dygraphs package itself.

[multi_dygraph_dashboard.zip](https://github.com/rstudio/dygraphs/files/402945/multi_dygraph_dashboard.zip)

**Comment by michelk** [comment]
I have the same issue, when using multiple dygraphs in an app.

**Comment by jjallaire** [comment]
Okay, this should now be fixed on master.
