### ISSUE TITLE
color argument in dyEvent should apply to label too, not just line

### ISSUE THREAD

**Issue by bearloga** [rstudio/dygraphs#122]
Howdy! I've tried messing with the HTML and the CSS of the resulting code but there's just no way that I've been able to change the color of the dyEvent labels so they match the lines.

We have a dashboard with a dark background so the default-black labels are totally hidden.

**Comment by jjallaire** [comment]
Could you send an example Rmd file which illustrates the problem?

**Comment by bearloga** [comment]
Sure! https://gist.github.com/bearloga/a87ec1e850ee313897b5a3126d131e37

Hopefully that example is OK. Thank you for looking into this!

**Comment by bearloga** [comment]
Thank you very much, @jjallaire! ^__^
