### ISSUE TITLE
input$dygraph_date_window returning NULL

### ISSUE THREAD

**Issue by aflyax** [rstudio/dygraphs#124]
For some reason, recently, the approach of returning input$dygraph_date_window in Shiny stopped working. We checked, and there were no changes to the code.

```
output$dygraph <- renderDygraph({
    dygraph(dt_xts, group = ‘blah', ylab = input$blah) 
      %>% dyOptions(colors = ‘seagreen’
                                 , drawGrid = FALSE
                                 , useDataTimezone = TRUE
                                 , retainDateWindow = T) %>%
      dyRangeSelector()
})
```

(The dygraph itself prints fine.)

```
  output$from_text <- renderText({
    paste('the time window is', input$dygraph_date_window)
  })
```

It doesn’t return anything after the initial string.

**Comment by jjallaire** [comment]
This was a regression in dygraphs 1.1.1 -- if you install from GitHub the
issue is resolved:

devtools::install_github("rstudio/dygraphs")

CRAN version with this fix will be released in ~ 3 weeks.

**Comment by jgabry** [comment]
Is the CRAN release containing this fix still imminent? Thanks

**Comment by jjallaire** [comment]
Yes, the CRAN release should be in the next few days.

**Comment by jgabry** [comment]
Great thanks!

**Comment by jjallaire** [comment]
The new version is on CRAN now.
