### ISSUE TITLE
x range for non-date type

### ISSUE THREAD

**Issue by baniani** [rstudio/dygraphs#132]
How can I get the range of selected x area? currently I am using dygraph_date_window but what is returns is something like 1970-01-01T00:00:01.023Z which is in date format. But the value is not date. What is the best way to get 23 instead of 1970-01-01T00:00:01.023Z.

**Comment by jjallaire** [comment]
This should be fixed here: https://github.com/rstudio/dygraphs/commit/ad95f744d2a2fc53ec7d17e7abcd8f30107b5ac5

**Comment by wolfpack12** [comment]
It looks like jjallaire is pushing a fix in the next release. Until that point, you can try this (sorry, it's a little clunky):

1000*(as.numeric(strptime(input$dygraph_date_window[[1]],format="%Y-%m-%dT%H:%M:%OSZ", tz="GMT")) - as.numeric(strptime("1970-01-01T00:00:00.000Z",format="%Y-%m-%dT%H:%M:%OSZ", tz="GMT")))
