### ISSUE TITLE
Hardcoded significant digits in asISO8601Time (utils.R)

### ISSUE THREAD

**Issue by wolfpack12** [rstudio/dygraphs#134]
I'm trying to force dygraphs to take numeric inputs and return back the values from input$dygraph_date_window. I want to use the selected range values as inputs for other reactive functions in Shiny. The logic I am using works by parsing each date_window value, formatting it to a POSIXct object, subtracting the initial date (1970-01-01), then converting to a numeric value. It works fine for values greater than 1, but input values less than 1 are rounded due to the hard coded 3 digit millisecond format in asISO8601Time.

Can you please change the code from this:

> format(x, format="%Y-%m-%dT%H:%M:%OS3Z")

To this:

> format(x, format="%Y-%m-%dT%H:%M:%OSZ")

I believe that change will allow the user to specify the number of significant digits using options("digits.secs"=x), where x is from 0 to 6.

**Comment by jjallaire** [comment]
I just made a change to the development version of dygraphs to return
actual numeric values in input$dygraph_date_window when the format !=
"date" so you should be able to get this working without any changes to the
format function.
