### ISSUE TITLE
why dySeries name parameter must either be a character vector of length one or three?

### ISSUE THREAD

**Issue by karina7rang** [rstudio/dygraphs#143]
why the length must be 1 or 3? any way to make this parameter more flexible?

**Comment by jjallaire** [comment]
Because traditionally there were either 1 series or 3 (for upper/lower bars). I guess though with candlestick charts you cold have 4 or even 5 series. Is your scenario for a candlestick chart or something else? (just want to understand the scenario we are solving for before making a change).

**Comment by karina7rang** [comment]
I need lines or bars not candlesticks chart actually... I use this in shiny app with a reactive number of series will apply in dygraphs. so in fact the number of series here could be 1,2,3,4,5....for now the max number is 10, but it could be larger later.
I think... I can use loop to create separate series instead of put them in one series. but it will be better i can use a simple line to achieve this goal.

**Comment by jjallaire** [comment]
Looking more closely at the code it is sensitive to 1 or 3 series so changing it would be more involved than I thought. For now I'd just use the loop.

**Comment by karina7rang** [comment]
ok... thanks...
