### ISSUE TITLE
Synchronization does not work with Flexdashboard

### ISSUE THREAD

**Issue by EnricowithR** [rstudio/dygraphs#154]
I tried to use within a Flexdashboard the Synchronization, as explained here:
http://rstudio.github.io/dygraphs/gallery-synchronization.html
However, the result is that only the first chart is shown and the others do not appear at all.
What should I do to show all the graphs in the same page, as in the synchronization tutotial ?

**Comment by jjallaire** [comment]
Flexdashboard is designed to show a single plot per layout region, so you really just need to place each dygraph in it's own layout area. This example demonstrates: https://beta.rstudioconnect.com/jjallaire/htmlwidgets-dygraphs/htmlwidgets-dygraphs.html (click the Source Code button on the top right to see the code).
