### ISSUE TITLE
Installation does not work 

### ISSUE THREAD

**Issue by danklotz** [rstudio/dygraphs#173]
Could be that it is only me. But might be a broader issue: 

If I try to install the github versio of `dygraphs` (by using `devtools::install_github(c("ramnathv/htmlwidgets", "rstudio/dygraphs"))`, I get the follwoing error message: 

`Error in namespaceExport(ns, exports) : undefined exports: dySliderInput`

**Comment by jjallaire** [comment]
Thanks for reporting, just fixed!

**Comment by danklotz** [comment]
Oh, wow! It does indeed work already. Thank you <3
