### ISSUE TITLE
tag releases on Github

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/dygraphs#204]
Would it be possible to start tagging releases on Github https://github.com/rstudio/dygraphs/releases?  Thanks!!!

**Comment by pshevtsov** [comment]
Yes, I was also thinking about it. And also I was thinking about utilizing some CI/CD solution to make testing, building and submitting to CRAN more smooth.

**Comment by pshevtsov** [comment]
https://github.com/rstudio/dygraphs/releases/tag/v1.1.1.5

**Comment by timelyportfolio** [comment]
@pshevtsov, awesome thanks!
