### ISSUE TITLE
ISO date format

### ISSUE THREAD

**Issue by bergant** [rstudio/dygraphs#21]
Hi!

On windows (R version 3.0.2) I get only empty graph. After some debugging I am pretty sure it is because "my" `format.POSIXct` returns empty string when formated as `"%F"`.

Maybe the `asISO8601Time` function in [dygraphs/R/utils.R](https://github.com/rstudio/dygraphs/blob/master/R/utils.R) could be changed to

```
asISO8601Time <- function(x) {
  if (!inherits(x, "POSIXct"))
    x <- as.POSIXct(x)
  format(x, format="%Y-%m-%dT%H:%M:%SZ")
}
```

For now my workaround is:

```
res1 <- dygraph(nhtemp, main = "New Haven Temperatures",  ylab = "Temp (F)") 
res1$x$data[[1]] <- format( attr(res1$x, "time"), "%Y-%m-%dT%H:%M:%SZ")
res1
```

Dare

**Comment by ChipMart92** [comment]
Hi, bergant.  This might be off topic, but I was hoping I could have your assistance with the XBRL files you posted Earlier. I was wondering how to apply this method to, say another company. Many thanks

**Comment by bergant** [comment]
@ChipMart92  I guess this has nothing to do with dygraphs. I have made my e-mail public on my account so you can contact me directly.
