### ISSUE TITLE
access information on user interaction with dygraph?

### ISSUE THREAD

**Issue by mostly-harmless** [rstudio/dygraphs#25]
Is it possible to access information on the user's input to dyRangeSelector or the brushed range? Suppose, for example, the available data ranges from 2001-2010 and the user has selected 2002-2005 using the range selector or brushing. Is that information accessible from R (Shiny)?

Thanks for a fantastic library!

**Comment by jjallaire** [comment]
@jcheng5 Do you have a suggested approach for htmlwidgets to make input variables available to the rest of the page? (in this case a brushed range from the dyRangeSelector). I could probably figure out a way to make this work but it seems like some sort of general mechanism would be desirable.

**Comment by mostly-harmless** [comment]
I asked a similar question about the DT package. There the interest is in saving user created filters for later use in various analyses. For dygraph something like the brusch_summary function used in gig is would already be really valuable (https://github.com/rstudio/ggvis/blob/master/demo/brush.r). You could also think of various tests (e.g., unit root) or forecasts that could be run based on the data range selected by the user. Or in the leaflet package based on the geographical area that is selected. Or in the DiagrammeR package, selecting a branch in the diagram to calculate the expected value of a business decision associated with that branch, etc. etc. There are many other areas I could think of where this type of feedback/input would useful in shiny-apps. A general mechanism to feed user interaction with the widget back to R could be incredibly valuable!

On a related, albeit higher level, note, giving acces to information/data/etc. from user interactions with a shiny app directly into Rstudio for 2-way communication would also be of great value (e.g., https://github.com/erikriverson/spyre).

**Comment by jcheng5** [comment]
I've been using `Shiny.onInputChange(outputId + "_selected_range", selectedRange)` (for example). Then you access the value using `input$outputid_selected_range` just like any other Shiny input.

**Comment by timelyportfolio** [comment]
this is helpful. will try this on other widgets.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/dygraphs/pull/26
