### ISSUE TITLE
dygraphs in Shiny application deployed over internet using Microsoft Azure [accessed in SG, FR and China] 

### ISSUE THREAD

**Issue by tanthiamhuat** [rstudio/dygraphs#256]
I have a shiny application with dygraph plots which is deployed over internet using Azure.
This application works well, able to show the dygraph plots when accessed over in Singapore and France.
But when accessed over in China, those dygraph plots DO NOT show up.

Surprised with this finding, I create similar plot in Shiny using plotly.
Surprisingly, that plotly plots are able to show well in Singapore, France and China.

What could be the hidden things which we are not aware?
This sounds to be very weird. Is the issue with dygraph itself?
Anyone encounter the similar issue?
Thanks.

**Comment by tanthiamhuat** [comment]
my very bad.. it is the timezone issue, I have solved it already...dygraphs is PERFECT

**Comment by GitHunter0** [comment]
@tanthiamhuat , so don't forget to please close the issue.
