### ISSUE TITLE
Use + instead of %>%

### ISSUE THREAD

**Issue by yutannihilation** [rstudio/dygraphs#27]
I feel no problem with `%>%`, but those who use `ggplot2` may be familiar with `+` to add layers.

What do you think about implementing `+.dygraph`, like [ggplot2](https://github.com/hadley/ggplot2/blob/4bb9270ef4d5d5062353438fd99d17b6f6de98a2/R/plot-construction.r#L63-L70)?

**Comment by jjallaire** [comment]
We're attempting to use %>% consistently across all of our packages (and all the other widgets I've seen use this as well) so I'm hopeful that this will become familiar to most users very soon.

**Comment by yutannihilation** [comment]
Thanks for your quick reply. I understand :)
