### ISSUE TITLE
Second Y-Axis with dygraphs

### ISSUE THREAD

**Issue by tungmilan** [rstudio/dygraphs#28]
I'm wondering if it's possible to plot something like this in case I want to have a secondary axis? Precipitation/rainfall was plotted from the top with type = "h". Thank you very much!

![topmodel_calibration_0103_final](https://cloud.githubusercontent.com/assets/6590141/5791531/4461b2a6-9e90-11e4-8953-8e9a2513e1bf.png)

**Comment by jjallaire** [comment]
Here is the documentation on adding a second Y axis:
http://rstudio.github.io/dygraphs/gallery-second-y-axis.html

**Comment by madtraveller** [comment]
Thanks! I went through that already. What I'm wondering is how to plot the rainfall upside down from the top as in the posted graph

**Comment by jjallaire** [comment]
For that you'd need to create a custom plotter (see:
http://dygraphs.com/options.html#plotter). You can specify a plotter
function on a per-series basis using the dySeries function and on a global
basis using the dyOptions function. Creating a custom plotter requires some
knowledge of JavaScript and 2d canvas graphics -- sorry there isn't an
easier way!

**Comment by madtraveller** [comment]
Than you jjallaire!

**Comment by ErwinDCI** [comment]
Hi tungmilan,

I'm looking for the exact same problem as you. Could you share youre code and plotter?
Do you also import your data from a csv?

Many thanks in advance!
Erwin
