### ISSUE TITLE
Datetimes displays in different time zone

### ISSUE THREAD

**Issue by gonzmg88** [rstudio/dygraphs#29]
Hi,

When I load a time series with an specific time zone in R and I plot it using dygraphs, time zones are displayed in sistem time zone (or browser time zone not sure which value is getting). Therefore time zone information of the ts object seems to be discarded.

```{r}
library(dygraphs)
library(xts)
datetimes<-seq.POSIXt(as.POSIXct("2015-01-01",tz="GMT"),
                      as.POSIXct("2015-01-07",tz="GMT"),by="3 hours")
values<-rnorm(length(datetimes))

serie<-xts(values,order.by = datetimes,tz="GMT")
head(serie)
dygraph(serie)
```

**Comment by jjallaire** [comment]
You can use the `useDataTimezone` option (specified in `dyOptions`) to preserve the timezone of the xts series. e.g. in your example:

```r
dygraph(serie) %>% 
   dyOptions(useDataTimezone = TRUE)
```

Note that this feature is not yet available in the CRAN version of dygraphs so you'll need to install it from github via `devtools::install_github` for the time being.

**Comment by gonzmg88** [comment]
thank you!

**Comment by jpgattuso** [comment]
I am plotting a time series which uses UTC.

dyOptions(useDataTimezone = TRUE) does not work for me, there is a *2 hours shift** between the plot and the data. I am using dygraphs 1.1.1.4 with Rstudio  1.0.136  on a Mac (10.12.3).

Thanks
