### ISSUE TITLE
Auto-refresh seems to confuse dygraphs

### ISSUE THREAD

**Issue by eddelbuettel** [rstudio/dygraphs#37]
We have some shiny-based dashboards where we refresh some standard R graphs on a refresh timers -- this works great but is not interactive.

Trying such code with dygraphs does not work so well.   The x-axis seems frozen to the old range.

Is this a known issue (I could not find any tickets) or a new one?   I could possibly mock something up.

**Comment by jjallaire** [comment]
In the simple example we ship in the package we have time series that is
updated with new ranges and it seems to work:

https://github.com/rstudio/dygraphs/tree/master/inst/examples/shiny

That said, I've definitely seen dygraphs have issues related to certain
options not being properly updatable. I guess worst case we could implement
a mode where we tear down and rebuild the dygraph completely. If you send a
short example I'll delve into this further.

**Comment by eddelbuettel** [comment]
Thanks for the link to a canonical example.  I will try to narrow the difference to my setup down to something.  FWIW I am using POSIXct intra-day.

**Comment by eddelbuettel** [comment]
JJ, I meant something else along the lines of 

```{.r}
invalidateLater(1000 * as.numeric(updateFreq[input$updatefreq]), session)
```

where the data comes from Redis, but we could easily mock with creating random walks.  I'll try to work on something.

**Comment by jjallaire** [comment]
Here's a reproducible example from @eddelbuettel:

```r
library(shiny)
library(dygraphs)
library(xts)

Sys.setenv(TZ="America/Chicago")
options("digits.secs"=6)

set.seed(42)

updatefreq <- 2                        # seconds
timeback <- 5                          # seconds
lastupdate <- Sys.time()

blues <- RColorBrewer::brewer.pal(5, "Blues")[-1]

D <- NULL

getxts <- function(timeback) {
  x1 <- rnorm(timeback)
  x2 <- rnorm(timeback)
  X <- xts(cbind(x1,x2), order.by=Sys.time() + seq(-timeback, -1))
}

ui <- shinyUI(fluidPage(
  
  ## Application title
  title = "Dygraph Demo",
  titlePanel("Dygraph Demo"),
  
  fluidRow(
    column(2,
           br(),
           wellPanel(
             helpText("Click and drag to zoom in (double click to zoom
                      back out).")
           )),
    column(10,
           br(),
           tabsetPanel(type="tabs",
                       tabPanel("Plots",
                                dygraphOutput("dygraphA",
                                              height="350px"),
                                br(),
                                dygraphOutput("dygraphB",
                                              height="350px")),
                       tabPanel("Data", tableOutput("data")))
    )
           )
))


server <- function(input, output, session) {
  
  data <- reactive({
    D <<- rbind(D, getxts(timeback))
    invalidateLater(1000 * updatefreq, session)
    D
  })
  
  output$dygraphA <- renderDygraph( {
    X <- data()
    dg <- dygraph(cumsum(X[,1]), main = "ABC", group="groupedplots")
    dg <- dyOptions(dg, colors = blues[4], stepPlot=FALSE, strokeWidth=2,
                    useDataTimezone=TRUE)
    dg <- dyRangeSelector(dg)
  } )
  
  output$dygraphB <- renderDygraph( {
    X <- data()
    dg <- dygraph(cumsum(X[,2]), main = "DEF", group="groupedplots")
    dg <- dyOptions(dg, colors = blues[4], stepPlot=FALSE, strokeWidth=2,
                    useDataTimezone=TRUE)
    dg <- dyRangeSelector(dg)
  } )
  
  output$data <- renderTable({
    X <- data()
    if (nrow(X) > 2) {
      data.frame(time=format(index(X)), as.data.frame(coredata(X)))
    }
  })
}

shinyApp(ui = ui, server = server)
```

@bthieurmel I don't think I know the timezone axis formatter code well enough to figure out what's going on here. Could you take a look?

**Comment by bthieurmel** [comment]
Hi, can you tell me a little bit more about the problem ? (I'm sorry but i'm not a very good english speaker...).
Is-it always a rangeSelector question or an axis / value formatter problem with the very close points ?

**Comment by eddelbuettel** [comment]
Salut mon pote,

In essence I tried to mock up a use case related to what we do at work, currently only with static graphs from R which get refreshed.  The base R-via-shiny case works, I was trying to use dygraphs but failed.   So I created an example which I emailed to JJ, and which he posted here,  In the email I said

> The code below doesn't exactly do what my first in-house (and Redis-based)
> updater with dygraphs, but it shows some other things:
> 
> 1) chart does not update; range selector does though
> 
> 2) tz information ignored for axis

and

> As always it is more refined.  Data does get added, but the plot does not get redrawn.

@jjallaire is looking into the redrawing/refreshing/rangeselector issues but (AFAICT) was wondering if you could look into the TZ aspect.  In short, I am UTC - 5 in Chicago, set a timezone, have the data displayed correctly in the second tab (via standard R) but dygraph still labels the axis wrongly.

**Comment by bthieurmel** [comment]
I can have a look in the week. A question to be sure : you are using dygraph 0.4.2, the CRAN version ?

**Comment by eddelbuettel** [comment]
Great -- and yes, I believe I use 0.4.2.   Because `update,packages()` does not know about Git(Hub), I have a strong preferences for actual repositories and I do keep my packages very current to those.

**Comment by bthieurmel** [comment]
I find the cause (and so we can have a solution). dygraphs R package apply a javascript date transformation if scale isn't in minute or hour (not second...) to render properly daily data. In the actual R CRAN package, this transformation is already active with useDataTimezone = TRUE.
I already fix it in a future ( perhaps ? @jjallaire ?) version of dygraphs, using 1.1 javascript library.
So the question is for @jjallaire : 
- can we fix it in actual version ? or can we plan to update dygraphs to 1.1 ?
and for @eddelbuettel :
- Do you want a fix version (with 1.1 javascript library) to test for the moment ?

**Comment by bthieurmel** [comment]
To resume, the second scale case data is not well compute actually

**Comment by eddelbuettel** [comment]
Yes please.  If you have a simple patch or change I would be delighted to test.

**Comment by bthieurmel** [comment]
You can use this version for test : 

https://github.com/bthieurmel/dygraphs/tree/feature/dygraphs-1.1

And, concerning the range selector, I don't know if it's the question, but you can update the rangeSelector when you update the graphics using dateWindow argument of dyRangeSelector

```
dg <- dyRangeSelector(dg, dateWindow = range(time(X)))
```

**Comment by eddelbuettel** [comment]
I am confused.  You call this dygraphs-1.1, your DESCRIPTION uses 0.4.1 (ie behind CRAN and RStudio's dygraph).

Could you pretty please provide either
+ a patch, or
+ a source package, ideally with a Version: that makes it distinct from the current CRAN version.

**Comment by bthieurmel** [comment]
Sorry for the confusion. Dygraphs-1.1 refer to the javascript version of dygraphs. The branch of the link is a R source package of the work we began with JJ Allaire to update javascript library in R package dygraph. It's why the description is still to 0.4.1...

It's good if you 'll want to test "quickly", before a cleaner fix.

**Comment by eddelbuettel** [comment]
I used https://raw.githubusercontent.com/bthieurmel/dygraphs/feature/dygraphs-1.1/inst/htmlwidgets/dygraphs.js together with stock 0.4.2. as a local 0.4.2.1; it does NOT work as
nothing is plotted anymore.

**Comment by bthieurmel** [comment]
Actual R package dygraph use dygraphs 1.0.1 javascript library. The link https://github.com/bthieurmel/dygraphs/tree/feature/dygraphs-1.1 use 1.1 javascript library, with a lot of change. So you can't just update dygraph.js without also update dygraphs library.

If you just want to change dygrahs.js, you can perhaps just change and test : 

```
 normalizeDateValue: function(scale, value) {
var date = new Date(value);
if (scale != "minute" && scale != "hourly" && scale != "second") {
var localAsUTC = date.getTime() + (date.getTimezoneOffset() * 60000);
date = new Date(localAsUTC);
}
return date;
}
```

at the end of htmlwidgets/dygraphs.js

**Comment by eddelbuettel** [comment]
I am sorry but I don't have time to chase library components around, and I do not speak JS.  

I would gladly test if you provided a patch, or tarball, as I suggested above.

**Comment by jjallaire** [comment]
I think we should try to fix it in the CRAN version for now as we still
haven't had time to iron out all of the axis size difficulties in the v1.1
pull request. Would it be straightforward for you to provide a PR against
the current master with just this fix?

On Mar 24, 2015, at 10:42 AM, Thieurmel <notifications@github.com> wrote:

I find the cause (and so we can have a solution). dygraphs R package apply
a javascript date transformation if scale isn't in minute or hour (not
second...) to render properly daily data. In the actual R CRAN package,
this transformation is already active with useDataTimezone = TRUE.
I already fix it in a future ( perhaps ? @jjallaire
<https://github.com/jjallaire> ?) version of dygraphs, using 1.1 javascript
library.
So the question is for @jjallaire <https://github.com/jjallaire> :

   - can we fix it in actual version ? or can we plan to update dygraphs to
   1.1 ? and for @eddelbuettel <https://github.com/eddelbuettel> :
   - Do you want a fix version (with 1.1 javascript library) to test for
   the moment ?

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/dygraphs/issues/37#issuecomment-85614740>.

**Comment by bthieurmel** [comment]
I think I can do a clean fix thursday on current CRAN version.

**Comment by jjallaire** [comment]
Okay, that's great. Much appreciated!

On Mar 24, 2015, at 1:09 PM, Thieurmel <notifications@github.com> wrote:

I think I can do a clean fix thursday on current CRAN version.

—
Reply to this email directly or view it on GitHub
<https://github.com/rstudio/dygraphs/issues/37#issuecomment-85673506>.

**Comment by eddelbuettel** [comment]
:+1: for minimal change fix against current release.

**Comment by bthieurmel** [comment]
If needed / wanted, you can find tar.gz of patch version her : 

https://github.com/bthieurmel/dygraphs/releases/tag/0.4.2-patch

**Comment by jjallaire** [comment]
Thanks @bthieurmel for the patch! I think we've got both issues resolved now. @eddelbuettel let us know if everything looks good on your end.

**Comment by eddelbuettel** [comment]
Thanks so much but I am not yet seeing ideal behaviour. :-/

As such I'd suggest to keep open.  I will see @jjallaire in a bit, maybe it is different on his machine.

(For the reproducibility record, I save my script posted by JJ above as app.R in a directory, and called shiny via `runApp()` on setting a port.)

One needs to manually pull the right rangeselector forward.  Can that be automated?  The line suggested above

      dg <- dyRangeSelector(dg)

does not do it.

**Comment by jjallaire** [comment]
Don't fully understand this reference "One needs to manually pull the right
rangeselector forward". Could you clarify? We can also cover in-person
later this morning if that's better.

On Thu, Mar 26, 2015 at 6:45 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Data grows. Plots stays static. I only see new data when I manually move the selector.

That is the opposite of what updating static graphs: by (forcibly) repainting the graph, you see the _new_ data.  Here we see the _old_ data. Less useful.

**Comment by eddelbuettel** [comment]
Weird. I works when I restart.  Maybe there is a startup race condition.

And the `TZ` is taken care of which is excellent.

**Comment by eddelbuettel** [comment]
I must have missed the `dyRangeSelector` change in the first instance.   

It's all good now, thanks so much to both of your.

**Comment by eddelbuettel** [comment]
Checked some more and yes, this really works well now.

One minor query:  can we influence the x-Axis format from the R side?

**Comment by jjallaire** [comment]
You can provide an axisLabelFormatter function (written in JavaScript)
via dyAxis. If your function needs to deal with the full generality of
axes with different granularities, time-zones, etc. then it might end
up being pretty complicated, but if it's very hard-wired into your
specific application then it might be pretty simple.

Here are the docs: http://dygraphs.com/options.html#axisLabelFormatter

**Comment by eddelbuettel** [comment]
Sounds good, will take a look.

Having one issue here at work -- upon regresh shiny goes down.  The mock-up doesn't do that so it may be Redis related.  I'll try to peek, but it may be a few days...
