### ISSUE TITLE
Loading new data into an existing dygraph does not refresh input$<dygraphId>_data_window property

### ISSUE THREAD

**Issue by sdbecker** [rstudio/dygraphs#43]
Good Day

First some preliminaries, I am using:

Rstudio v 0.98.1103; R v 3.1.3 (32 bit), Shiny v 0.11.1, dygraphs v 0.4.3 ; this is on windows 8.1.

I would appreciate any help with respect to the issue of resetting the input$<dygraphid>_date_window property  (referred to as '_date_window' property here on) in shiny. 

When my shiny application loads up and the first instance of the dygraph is created the '_date_window' property is responsive and outputs the correct dates pertaining to the graph. Further when highlighting the graph to zoom in and double clicking on the graph to reset the zoom the  '_date_window' property is responsive and changes accordingly.

The problem arises when I attempt to load a different data set into the graph. For some reason, beyond my abilities to understand, the '_date_window' property retains the previous data set's dates. That is, when the new data set is included and the graph renders a new picture, everything looks good except for the simple fact that the '_date_window' property will not change to reflect the new data's dates.

I have included a one file demonstration of this problem below, that can be copied and pasted directly into the interactive console.

The code below, downloads prices for General Electric (GE) and Facebook (FB). Then plots the returned 'Close' prices to the dygraph of the selected entry in the selectInput object.

The point to note is that once a time series is loaded the respective start and end dates are shown in the textOutput objects. Therefore you can see how these respective start and end dates don't change when a new stock code is selected. Thus prompting the application to redraw the closing prices, but for some reason not updating the '_data_window' property.

Any guidance with respect to this issue would be appreciated, as I really do like using dygraphs!

#*********************************************************************

library(quantmod)
library(dygraphs)

getSymbols(c("GE", "FB"), src = "yahoo")

portf <- list()

portf$FB <- FB$FB.Close
portf$GE <- GE$GE.Close

server <- function(input, output) {
   
    
    output$dygraph <- renderDygraph({
        
        input$scode
        dygraph(portf[[input$scode]])
        
    })
    
    output$frmDate <- renderText({
        
        if (!is.null(input$dygraph_date_window))
            strftime(input$dygraph_date_window[[1]], "%d %b %Y")   
        
    })
    
    output$toDate <- renderText({
        
        if (!is.null(input$dygraph_date_window))
            strftime(input$dygraph_date_window[[2]], "%d %b %Y")   
        
    })
}

ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(
           selectInput("scode", "Code", choices = c("FB", "GE")),
           textOutput("frmDate"),
           textOutput("toDate")
           ),
        mainPanel(
            dygraphOutput("dygraph")
            )
    )
)

shinyApp(ui = ui, server = server)

'#######################################################

**Comment by jjallaire** [comment]
This behavior is by design, mostly to accommodate the scenario of realtime
updates to datasets every few seconds. In this case, if the user has zoomed
in on the series it's highly disruptive & unpleasant to zoom back out
automatically when the series acquires new data.

Realize that you have an entirely different use case (especially with your
series having distinct scales). In the case that your series had the same
scales I guess you could argue either way what the preferred behavior for
the end user would be (preserve vs. blow away current zoom window).

**Comment by sdbecker** [comment]
In an odd way, that is a relief.  Happy to know that it is by design and not something misunderstood or simply missing on my side. Thank you, I shall find another avenue for my application.

**Comment by jjallaire** [comment]
There is now a `retainDataWindow` option to control this. See https://github.com/rstudio/dygraphs/commit/75b29767f003ff4a24ebbec51acdeb84f635db4f

**Comment by sdbecker** [comment]
Good man, thanks for the update.
