### ISSUE TITLE
Issue with datatable (DT) and dygraph (dygraphs) in same Rmd

### ISSUE THREAD

**Issue by dnegrey** [rstudio/dygraphs#44]
*I am running into issues when trying to produce a DT::datatable and a dygraphs::dygraph in the same R markdown file. Upon rendering, the dygraph is not present in the HTML file. Below is a minimally reproducible example of my R code and my Rmd file (test.Rmd).*

**library(rmarkdown)
render("./test.Rmd")**

    ---
    title: "test"
    author: "Mr. Test"
    date: "Tuesday, April 14, 2015"
    output: html_document
    ---
    
    ```{r}
    # R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
    # Copyright (C) 2014 The R Foundation for Statistical Computing
    # Platform: x86_64-w64-mingw32/x64 (64-bit)
    
    # DT version is: 0.0.25
    library(DT)
    
    # dygraphs version is: 0.4.3
    library(dygraphs)
    ```
    
    
    ```{r}
    datatable(iris)
    ```
    
    ```{r}
    dygraph(mdeaths)
    ```

**Comment by jjallaire** [comment]
Just tried to repro and to do so installed the latest DT from GitHub (0.36). It worked in my configuration.

@yihui Was there an issue in DT that was resolved after 0.25 that might have caused this.

**Comment by dnegrey** [comment]
I just updated DT to version 0.0.36. This required that the htmlwidgets package also get updated to version 0.3.3.The same code and Rmd file now work fine. Thank you for the immediate response!

**Comment by yihui** [comment]
I do not know which commit(s) fixed the problem (https://github.com/rstudio/DT/compare/39d4080117...a4fb409b91f) since I do not know what exactly the problem was, but it is certainly better to use htmlwidgets >= 0.3.3 as required by the current version of DT.
