### ISSUE TITLE
Feature Request: Millisecond Plotting

### ISSUE THREAD

**Issue by JamesRTOK** [rstudio/dygraphs#46]
Hi,

Great graphing tool, thank you. 
I believe you are already incorporating rChartsDygraphs from danielkrizian.

Someone previously discussed millisecond plotting with that library. 
It would be very useful if the rstudio version of dygraphs could automatically detect and correctly plot
millisecond (or microsecond) level XTS data.

For example, the following is a microsecond stamped XTS series which gets pruned down to per second data

```
len <- 60 * 60  + 10
RDData <- xts(runif(len,0,1), seq(as.POSIXct("2015-04-01 10:00:00"),  as.POSIXct("2015-04-02 15:00:00"), length = len),tz="GMT")
dygraph(RDData) %>%  dyOptions(useDataTimezone = TRUE)
```
 
The dygraphs workaround is to use axisLabelFormatter and valueFormatter  but I don't see these parameters supported in the current rstudio implementation.

Thanks

**Comment by jjallaire** [comment]
The `dyAxis` function supports providing both an `axisLabelFormatter` and `valueFormatter`.

**Comment by JamesRTOK** [comment]
Thank you very much for the quick reply.
Sorry I didn't see the support for axisLabelFormatter and valueFormatter in the documentation.

Unfortunately, the following does not produce any graph.
I was wondering if you could tell me where I'm going wrong

```
CustomAxisLabel <- 'function (d, gran) {
                              return Dygraph.zeropad(d.getHours()) + ":" + 
                                     Dygraph.zeropad(d.getMinutes()) + ":"" + 
                                     Dygraph.zeropad(d.getSeconds()) + "." + 
                                     Dygraph.zeropad(d.getMilliseconds());
                             }'
CustomValueFormat = 'function (ms) {
                          var d = new Date(ms);
                          return Dygraph.zeropad(d.getHours()) + ":" + 
                          Dygraph.zeropad(d.getMinutes()) + ":" + 
                          Dygraph.zeropad(d.getSeconds()) + "." + 
                          Dygraph.zeropad(d.getMilliseconds());
                         }'


len <- 60 * 60  + 10
RDData <- xts(runif(len,0,1), seq(as.POSIXct("2015-04-01 10:00:00"),  as.POSIXct("2015-04-02 15:00:00"), length = len),tz="GMT")
dygraph(RDData) %>%  dyOptions(useDataTimezone = TRUE) %>% dyAxis("x",axisLabelFormatter =JS(CustomAxisLabel),valueFormatter=JS(CustomValueFormat)) 
```

**Comment by jjallaire** [comment]
I would check the JavaScript console to see if there is a problem (e.g.
exception being thrown) in the JavaScript code. Also, I don't believe you
need the JS function as a wrapper (I think we do that internally already).

**Comment by JamesRTOK** [comment]
Thanks.

There was a syntax error in my earlier post
```
 Dygraph.zeropad(d.getMinutes()) + ":" + 
```

Java console reports 

TypeError: 'undefined' is not a function (evaluating 'd.getHours()')

**Comment by kuna-matata** [comment]
See http://stackoverflow.com/questions/31299871/dygraph-millisecond-plotting for corrections to make this at least display. However, it still appears to ignore the fractional seconds and truncate or round to the nearest second. Perhaps dygraphs has a limitation to only support one second time resolution.
