### ISSUE TITLE
Viewer problem using a loop ?

### ISSUE THREAD

**Issue by TitouanRobert** [rstudio/dygraphs#50]
Hi,

Trying to print several dygraphs plot in a loop, nothing appear. It's seems it's not a dygraphs problem, but perhaps more globally a viewer problem. Can you ever heard about that ?

````
for(i in 1:2){
  lungDeaths <- cbind(mdeaths, fdeaths)
  dygraph(lungDeaths)
  readline(prompt = "next : ")
}
````

**Comment by jjallaire** [comment]
If you aren't at the console you need to explicitly print the dygraph, e.g.

print(dygraph(lungDaths))

**Comment by TitouanRobert** [comment]
Thank you, i have forgotten this function.
