### ISSUE TITLE
Option to allow loading new data into an existing dygraph -AND- refreshing input$<dygraphId>_data_window property

### ISSUE THREAD

**Issue by Stephen-McDaniel** [rstudio/dygraphs#51]
Hi JJ,

First, great work on this project! Beautiful.

I would ask you to consider addressing issue https://github.com/rstudio/dygraphs/issues/43 with a new option defaulted to keep the behavior as you have designed.  There is a whole class of problems in the data exploration space (vs real-time monitoring space) that would benefit from this enhancement.

I would suggest the option dateWindowRefresh = FALSE by default and dateWindowRefresh = TRUE, which would allow the user to stay zoomed in -and- the input$<dygraphId>_date_window to continue updating on data refresh.

**Comment by jjallaire** [comment]
Resolved via https://github.com/rstudio/dygraphs/commit/75b29767f003ff4a24ebbec51acdeb84f635db4f (note that the defaults remains `retainDataWindow = TRUE` for compatibility with existing behavior).
