### ISSUE TITLE
dyLimit example in gh-pages fails to work (js exception)

### ISSUE THREAD

**Issue by jjallaire** [rstudio/dygraphs#52]
@jrowen, When I attempt to build the gh-pages site the dyLimit function examples fails to render (see error state below). Could you take a look and see if you can resolve this? Thanks!

![screen shot 2015-05-08 at 12 13 28 pm](https://cloud.githubusercontent.com/assets/104391/7540462/f0f168bc-f57b-11e4-8367-f193ae8f1fa8.png)

**Comment by jjallaire** [comment]
@jrowen I put this through JSONLint and I think the issue relates to how the event info is composed (one of the list items may lack a name). See below:

![screen shot 2015-05-08 at 12 22 52 pm](https://cloud.githubusercontent.com/assets/104391/7540609/18b7f950-f57d-11e4-91d4-dd95757c2a94.png)

BTW you can repro this by just executing the code at the console and seeing the plot in the Viewer.

**Comment by jjallaire** [comment]
Resolved by making sure MSFT[1, 4] was serialized to json as a plain numeric value:

https://github.com/rstudio/dygraphs/commit/e62b710933ba14e0c8f645955fe4dec0a39e5066

**Comment by jrowen** [comment]
Thank you.  This would have taken me a while to figure out.
