### ISSUE TITLE
Range selector not working after recomputing the data

### ISSUE THREAD

**Issue by csese** [rstudio/dygraphs#56]
Hi, 
I am trying to control an external network graph using the dygraph range selector. 
On my shiny app, I have some checkbox. When I check or uncheck the boxes, it changes the data on the dygraph. 
However, after the first time I check one box, the dygraph range selector does not output the right start and end value anymore.  

See the reproducible example here: 
library(shiny)
library(dygraphs)
library(xts)

ui <- shinyUI(fluidPage(
        
        ## Application title
        title = "Dygraph Demo",
        titlePanel("Dygraph Demo"),
        
        fluidRow(
                dygraphOutput("dygraph1", height = '350px') ,
                fluidRow(column(7, verbatimTextOutput("fromY1"))),
                checkboxGroupInput("datachoice", label = "Data Choice",
                                   choices = c("+10"  = 1, "+20" = 2, 
                                               "+30" = 3),
                                   selected = 1)
        )
))

server <- function(input, output, session) {
        
        data <- reactive({
                lungDeaths <- cbind(ldeaths, mdeaths, fdeaths)
                for (k in seq_along(as.numeric(input$datachoice))){
                        lungDeaths <- lungDeaths + 10*k   
                }
                lungDeaths
               
        })
        
        output$dygraph1 <- renderDygraph( {
                X <- data()
                dg <- dygraph(X) 
                dg <- dyRangeSelector(dg,dateWindow = NULL,height = 40,fillColor = " #A7B1C4", strokeColor = "#808FAB") 
        } )
        output$fromY1 <- renderText({
                if (!is.null(input$dygraph1_date_window)){
                        
                        paste(strftime(input$dygraph1_date_window[[1]], '%Y-%m-%d'),
                              strftime(input$dygraph1_date_window[[2]], '%Y-%m-%d'), sep = ' to ')
                        
                }
                
                
        })
        
        
}

shinyApp(ui = ui, server = server)

You will see the data change if you do not check any of the boxes. However as soon as you change the boxes the date does not change anymore. 
I am not sure why this is happening. 

Thanks.

**Comment by jjallaire** [comment]
Thanks for reporting this. This is a regression based on a recent chnage. You can install the fixed version from GitHub as follows:

```r
devtools::install_github("rstudio/dygraphs")
```

We'll release a new version to CRAN with this fix within the next couple of weeks.

**Comment by csese** [comment]
That's working perfectly now. 
Thank you very much. 
Charles
