### ISSUE TITLE
Disabling scientific notation?

### ISSUE THREAD

**Issue by Ironholds** [rstudio/dygraphs#57]
If I set options(scipen=500) I still end up using scientific notation in dygraphs for numbers below that limit (but above the default). Is this a dygraph bug, a non-configurable option, ...?

**Comment by jjallaire** [comment]
dygraphs doesn't do anything special to reflect the underlying R options
visa-vi scientific notation. You can tweak this manually using dyOptions
(see docs for the available options including sigFigs here:
http://dygraphs.com/options.html)

**Comment by Ironholds** [comment]
Makes sense; what would you think of a patch modifying dyOptions so that the options(scipen) value is selected as the default?

**Comment by jjallaire** [comment]
Yes, that would be very welcome. I don't know if there is a direct mapping
between the scipen concept and the sigFigs and maxNumberWidth arguments. In
that case you probably need to send getOption("scipen") down to JavaScript
and then resolve the sigFigs and maxNumberWidth arguments using it *only
if* they aren't already explicitly specified.

**Comment by JhossePaul** [comment]
You could use the dyAxis function to specify the javascript function to format labels. Something like that should work

```{r}
dyAxis("y", label = "",
           axisLabelFormatter = JS("function formatValue(v){return String(v)}"),
           valueFormatter = JS("function formatValue(v){return String(v)}"))
```
