### ISSUE TITLE
Is it possible to draw candlestick graph?

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/dygraphs#6]
Financial time series is an important category of time series data. Is it possible for dygraphs to draw candlesticks given open, high, low, close data (matrix or data frame)?

If there's a demo, that would be great!

**Comment by TonyDIRL** [comment]
Hi, 

I was wondering if these candlesticks features had be incorporated into the package?

Thanks

**Comment by danielkrizian** [comment]
@renkun-ken PR is here: https://github.com/rstudio/dygraphs/pull/128
