### ISSUE TITLE
dateWindow to return only the final date

### ISSUE THREAD

**Issue by csese** [rstudio/dygraphs#60]
Hi, 

Using the range selector, I am controlling multiple other objects in shiny. 
The datewindow values changes constantly even though the user did not release the cursor. 
Therefore those objects have to be updated for every change when actually only the last date returned by the range selector is of importance. 
Is there a way to only output the last date/ time? 

Thanks

**Comment by jjallaire** [comment]
@jcheng5 The dateWindow drives a Shiny input variable. Are there generic
shiny debouncing functions that the user could apply to achieve what they
are hoping here?

**Comment by jcheng5** [comment]
We don't really have ad-hoc debouncing, no, but that would be good to add. Surprising it hasn't come up more often. It would be possible to write one on top of the existing Shiny reactive primitives (`reactive`, `reactiveValues`, and `invalidateLater`).

**Comment by csese** [comment]
Thank you for your answers.
I am not sure on how to design a debouncing object so any help is welcomed.
In the mean time, I found that there is no bouncing when the user in zooming on the graph. 
Maybe, a similar approach can be used to solve this problem.

**Comment by jcheng5** [comment]
OK, here's a debounce function. See the example at the bottom. https://gist.github.com/jcheng5/6141ea7066e62cafb31c

**Comment by csese** [comment]
Thanks a lot that's very helpful!
