### ISSUE TITLE
Cannot set strokeWidth per-series 

### ISSUE THREAD

**Issue by d-qn** [rstudio/dygraphs#61]
First, a big thank you for this great R package!

I can't manage to set the strokewidth per-series and it is mentioned in the help page that one can do it. 

For instance, I believe the short code snippet under should set the strokewidth per series (as it is with colours)

```
library(dygraphs)
dygraph(cbind(ldeaths, mdeaths, fdeaths), main = "Deaths from Lung Disease (UK)") %>%
  dyOptions(colors = c("green", "blue", "red"), strokeWidth = c(1,3,5))
```
The resulting line chart with the code above have all the same strokeWidth. But setting strokeWidth globally for all series works:

```
library(dygraphs)
dygraph(cbind(ldeaths, mdeaths, fdeaths), main = "Deaths from Lung Disease (UK)") %>%
  dyOptions(colors = c("green", "blue", "red"), strokeWidth = 10)
```

**Comment by jjallaire** [comment]
To set per-series properties you need to use the `dySeries` function, see http://rstudio.github.io/dygraphs/gallery-series-options.html#per-series-options

**Comment by d-qn** [comment]
Doh! Thank you
