### ISSUE TITLE
Synchronization of dygraphs in Shiny apps

### ISSUE THREAD

**Issue by spotter** [rstudio/dygraphs#62]
Plotting a single dygraph in a Shiny app works really well. However, **when trying to plot several dygraphs** (and using the group option to synchronize them as shown in [the doc](https://rstudio.github.io/dygraphs/gallery-synchronization.html)) doesn't seem to work.

**Comment by jjallaire** [comment]
We had some issue with multiple plots in Shiny in the last release however
the most recent version of dygraphs from CRAN should overcome them. Could
you try installing the new dygraphs v0.4.5 from CRAN to see if the problem
still occurs? You should also install the latest version of htmlwidgets
(v0.5) from CRAN as I believe some changes there also have an impact.

If it does then I'd appreciate if you could put together a minimum
reproducible example with sessionInfo, etc. and I can look at it further.

**Comment by spotter** [comment]
The libraries have the same version number as the ones you mention. Could it be the version of R?
I also added a code sample that only produces one plot (the last one) where there should be three according to [the doc](https://rstudio.github.io/dygraphs/gallery-synchronization.html).

Here is my sessionInfo():

```R
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dygraphs_0.4.5 shiny_0.12.1   xts_0.9-7      zoo_1.7-12    

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6       lattice_0.20-31   digest_0.6.8      mime_0.3          grid_3.2.0        R6_2.0.1         
 [7] xtable_1.7-4      jsonlite_0.9.16   magrittr_1.5      rstudioapi_0.3.1  tools_3.2.0       htmlwidgets_0.5  
[13] httpuv_1.3.2      yaml_2.1.13       htmltools_0.2.6   rstudio_0.98.1103
```

And here some sample code

*ui.R:*

```R
library(dygraphs)

shinyUI(fluidPage(    
    titlePanel("Tarkett variables"),

    sidebarLayout(
      sidebarPanel(selectInput("dataset", "Dataset:", c("lungs"))),
      
      mainPanel(dygraphOutput("lungDygraph"))
    )
  )
)
```

*server.R:*

```R
library(dygraphs)

shinyServer(
  function(input, output) {
    output$lungDygraph <- renderDygraph({
      dygraph(ldeaths, main = "All", group = "lung-deaths")
      dygraph(mdeaths, main = "Male", group = "lung-deaths")
      dygraph(fdeaths, main = "Female", group = "lung-deaths")
    }) 
  }
)
```

**Comment by jjallaire** [comment]
The problem here is that you need separate dygraphOutput calls for each
dygraph you want to show (in your example only the last dygraph is actually
returned from the function and displayed, this works differently in Shiny
where you are writing a function that returns a value as opposed to R
Markdown where you are just printing things in sequence).

**Comment by spotter** [comment]
Thank you for the fast reply! It works. However, in my application, the number of plots will depend on an input variable, so I'll need a ```for``` loop (or a ```lapply``` ) on the server side. Maybe putting the variable in *global.R* could help. Nevertheless, this is a different issue, so I guess this one can be closed ;-)

**Comment by Haycen** [comment]
Hello, 

I have the same issue but without using shiny. Basically, I'm not able to display 3 plots in the same window with dygraph as mentioned [here](https://rstudio.github.io/dygraphs/gallery-synchronization.html). When I try this code : 
```
dygraph(ldeaths, main = "All", group = "lung-deaths")
dygraph(mdeaths, main = "Male", group = "lung-deaths")
dygraph(fdeaths, main = "Female", group = "lung-deaths")
```
The graphs appear in separate windows.

**Comment by jjallaire** [comment]
If you want them in the same window they should be included in an R Markdown document rather than executed at the Console. Here's a simple Rmd that illustrates:

    ---
    title: "Synchronization"
    ---

    ```{r, include=FALSE}
    library(dygraphs)
    ```

    ```{r, echo=FALSE,fig.height=2.0}
    dygraph(ldeaths, main = "All", group = "lung-deaths")
    dygraph(mdeaths, main = "Male", group = "lung-deaths")
    dygraph(fdeaths, main = "Female", group = "lung-deaths")
    ```

**Comment by Haycen** [comment]
Thanks, it works.

**Comment by Patrikios** [comment]
Hi I got a bit different problem. I got in one shiny dashboard app.
I am using 2 R dygraphs  in it. I observe a problem returning the graphs, that is, sometimes it doesn't load/display one of the dygraphs, sometimes it does. At the moment they both just don#t apear. Weird behaviour. Anyone experienced something similar?

Contexts:

ui
   
    library(zoo)
    library(dygraphs) 
 
    ...
    tabName="time",
      fluidRow(
        tabBox(width = 350,
               tabPanel(title="Product", dygraphOutput("dygraph1")),
               tabPanel(title="Segment", dygraphOutput("dygraph2")) 
    ...
server

      })

      zoo<-structure(c(2252L, 2256L, 2256L, 2257L, 2259L, 2262L, 2262L, 
                    2262L, 765L, 767L, 767L, 769L, 768L, 769L, 774L, 706L, 
                    16239L, 16220L, 26184L, 26148L, 26091L, 26099L, 26118L, 
                    12607L), .Dim = c(8L, 3L), .Dimnames = list(NULL, c("A", 
                    "B", "C")), index = structure(c(16849, 16853, 16854, 
                    16855, 16856, 16857, 16858, 16859), class = "Date"), class =     
                    "zoo")

      zoo2<-structure(c(52L, 56L, 56L, 57L, 59L, 62L, 62L, 
                     62L, 65L, 67L, 67L, 69L, 68L, 69L, 74L, 76L, 
                     162L, 162L, 261L, 261L, 260L, 260L, 261L, 
                     126L), .Dim = c(8L, 3L), .Dimnames = list(NULL, c("D", "E",             
                     "F")), index = structure(c(16849, 16853, 16854,16855,  
                     16856, 16857, 16858, 16859), class = "Date"), class = "zoo")

      output$dygraph1<-renderDygraph({
        dygraph(zoo)%>%
        dyOptions(stackedGraph = TRUE, drawGrid = FALSE) %>%
        dyRangeSelector(height = 20)%>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))
      
      })
  
      output$dygraph2<-renderDygraph({
        dygraph(zoo2) %>%
        dyOptions(stackedGraph = TRUE,drawGrid = FALSE) %>%
        dyRangeSelector(height = 20) %>%
        dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))
      
      })
I am running R Studio v. 0.99.484, R v. 3.2.3, Windows Machine, Dygraphs Package v. 0.7, shinydashboard 0.5.1.

**Comment by jjallaire** [comment]
What version of htmlwidgets are you running?

We just fixed a bug in htmlwidgets (submitted to CRAN within the last 7
days) that affected display of dygraphs within bootstrap tabs. Hopefully
installing the updated version resolves this problem.

**Comment by Patrikios** [comment]
htmlwidgets v. 0.5.
Hope the fix will solve my issue as well as I like dygraphs for ts visualisation.

**Comment by jjallaire** [comment]
Okay, then you should try htmlwidgets v0.6 from CRAN. Hopefully that will
take care of it!

**Comment by Patrikios** [comment]
The htmwidgets magic happened after update to v. 0.6, dygraphs appear properly, thnx for help!

**Comment by jjallaire** [comment]
Great, glad it works now!

**Comment by sflorezp** [comment]
@spotter can you tell me how you resolve this issue?? 

I have th same problem in my shiny app :(
