### ISSUE TITLE
Saving Dygraph to PNG

### ISSUE THREAD

**Issue by joh024** [rstudio/dygraphs#71]
I would like to have a button in my shiny app to export Dygraph output to a PNG.

[dygraphs-export](http://cavorite.com/labs/js/dygraphs-export/) provides the functionality to do this, but I can't see any way to select the Dygraph object after it's created using the R package, which would be required to use dygraphs-export.

1. Is it possible to select the Dygraph object once created using the R package? (i.e. is it saved somewhere in a JavaScript variable?)
2. Can you incorproate dygraphs-export into the package to make it easy for other users to also use dygraphs-export and export to PNG? I'd say it'd be a welcome feature.

Thanks.

**Comment by joh024** [comment]
Used callbacks to achieve desired effect. Would still be nice to have it integrated, but I'll close this.

**Comment by discoraj** [comment]
Any chance you can share your solution?

**Comment by joh024** [comment]
Sorry for the slow response, I had to confirm some copyright details.

Have a look here: https://github.com/joh024/dygraph-extra

**Comment by echaintreau** [comment]
there is also the possibility to pass by htmlwidgets and webshot

htmlwidget to save as HTML and webshot to transform html to widget

`R
library(dygraphs)
library(htmlwidgets)
library(webshot)

## create map
m <- dygraph(lungDeaths) %>% dyRangeSelector()

## save html to png
saveWidget(m, "temp.html", selfcontained = FALSE)
width<- 1080
height <- 610
webshot("temp.html", file = "Rplot.png",
        cliprect = c(10,30,width+50,height+50)
        ,vwidth = width, vheight = height )
`
you can play on vwidth, vheight and cliprect to recenter your image just try some value for scale and it should be fine
