### ISSUE TITLE
Support alpha in dyEvent and dyShading

### ISSUE THREAD

**Issue by AMarthaller** [rstudio/dygraphs#73]
It would be great if dyEvent and dyShading supported alpha. I have some dyShading's that overlap and it's impossible to see where one ends and the other begins. For dyEvent, although the line color can be changed it would be nice if the text could be changed as well. I would also like alpha for dyEvent because the graph can become very noisy and sometimes it makes sense to have annotations that fade into the background.

**Comment by rozling** [comment]
Unless I'm mistaken this was an issue with Dygraphs but was fixed here: https://github.com/danvk/dygraphs/pull/594 - perhaps this can now be fixed in dygraphs for r?

**Comment by jjallaire** [comment]
This code should now work (note that we've recently also made a change to have the text color reflect the line color):

```r
dygraph(presidents, main = "Quarterly Presidential Approval Ratings") %>%
  dyAxis("y", valueRange = c(0, 100)) %>%
  dyEvent("1950-6-30", "Korea", labelLoc = "bottom", color = "rgba(255, 0, 0, 0.3)") %>%
  dyEvent("1965-2-09", "Vietnam", labelLoc = "bottom")
```

This code should also now work:

```r
dygraph(nhtemp, main = "New Haven Temperatures") %>% 
  dyShading(from = "1920-1-1", to = "1930-1-1", color = "rgba(255, 0, 0, 0.3)") %>%
  dyShading(from = "1940-1-1", to = "1950-1-1")
```

So I think alpha is indeed now supported in both places via rgba color specifications.
