### ISSUE TITLE
convert data frame to xts before plotting with dygraphs?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/dygraphs#78]
I just discovered this package and I'm trying to play with it. My data is in a data frame like this one:

    df1 <-
      structure(
        list(
          month = structure(
            1:12, .Label = c(
              "Apr", "May",
              "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb",
              "Mar"
            ), class = c("ordered", "factor")
          ), count = c(
            2492L, 2443L,
            2070L, 2999L, 2468L, 2285L, 3003L, 2467L, 3271L, 2979L, 2581L,
            3601L
          ), prct = c(
            5.17656500802568, 4.25706099058535, 5.16908212560386,
            5.90196732244082, 4.13290113452188, 6.17067833698031, 3.99600399600399,
            7.13417105796514, 4.46346682971568, 5.27022490768715, 6.12165827198761,
            6.2204943071369
          )
        ), .Names = c("month", "count", "prct"), class = "data.frame", row.names = c(NA,-12L)
      )

If i understand correctly, I have to convert my data to `xts` before I can use it with `dygraphs`. Correct?

I tried this:

    library(xts)
    df1<- df1 %>% xts(order.by = month)

but I get an error:

    Error in xts(., order.by = month) : 
      order.by requires an appropriate time-based object

How can I fix this?

Thanks!

**Comment by timelyportfolio** [comment]
@ignacio82, you'll need `month` in a date format. From the `xts` documentation:

```
The specified value must be a character string containing one of the following: Date, POSIXct, chron, yearmon, yearqtr or timeDate.
```

**Comment by ignacio82** [comment]
@timelyportfolio thanks. Do you know what is the best way of converting an ordered factor to a data format?

**Comment by timelyportfolio** [comment]
there are many ways, but I want to make sure I add the caveat that this is not appropriate if you are aggregating by month for things like seasonality.

```
library(xts)
library(dygraphs)
countspermonth %>%
  mutate( date = as.yearmon( c(rep(2014,9),rep(2015,3)) + (month-1)/12 ) ) %>%
  
```

**Comment by ignacio82** [comment]
@timelyportfolio a couple of questions:

1. In your code is `countspermonth` the same as `df1` in my question? If so, your code is not working on my computer :(

    Error in xts::periodicity(data) : 
      can not calculate periodicity of 1 observation
    In addition: Warning message:
      In Ops.ordered(1:12, 1) : '-' is not meaningful for ordered factors

2. Can you expand on your caveat? If my data is daily i should, and I want to aggregate it to monthly I should not do this?

Thanks a lot!

**Comment by ignacio82** [comment]
This works:

    countspermonth <-
      structure(
        list(
          yearmon = structure(
            c(
              2014.25, 2014.33333333333,
              2014.41666666667, 2014.5, 2014.58333333333, 2014.66666666667,
              2014.75, 2014.83333333333, 2014.91666666667, 2015, 2015.08333333333,
              2015.16666666667
            ), class = "yearmon"
          ), count = c(
            2492L, 2443L,
            2070L, 2999L, 2468L, 2285L, 3003L, 2467L, 3271L, 2979L, 2581L,
            3601L
          ), requierecrt = c(
            5.17656500802568, 4.25706099058535, 5.16908212560386,
            5.90196732244082, 4.13290113452188, 6.17067833698031, 3.99600399600399,
            7.13417105796514, 4.46346682971568, 5.27022490768715, 6.12165827198761,
            6.2204943071369
          )
        ), .Names = c("yearmon", "count", "prtg"), class = "data.frame", row.names = c(NA,-12L)
      )
    
    qxts <- xts(countspermonth[,-1], order.by=countspermonth[,1])
    
    dygraph(qxts) %>%
      dyAxis("y", label = "Number of ads") %>%
      dyAxis("y2", label = "% of ads that mentioned a certificate", independentTicks = TRUE) %>%
      dySeries("prtg", axis = 'y2')

I would still love to read more about your caveat @timelyportfolio

**Comment by timelyportfolio** [comment]
library(magrittr) will I think fix the problem, or an update to the newest magrittr might also get the expected result.

So in regards to the caveat, a lot of times with time series a user might aggregate over months for multiple years with something like mean.  In that case, you wouldn't want to convert to xts and dygraphs probably would not be the best option.}
