### ISSUE TITLE
Need a param in dySeries to pass the 'showInRangeSelector' flag

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/dygraphs#79]
http://dygraphs.com/options.html#showInRangeSelector, allows to selectively exclude/include series from RangeSelector. As it stands now, dySeries has no way of specifying this flag.

Perhaps a more generic issue should be for dySeries, dyOption to support all Series / Global Options in the JS lib.

**Comment by hug-fr** [comment]
This issue has been closed but does the concerned option has been implemented ? It does not seem so... I took a look at dySeries and dyOption and did not find it. This option could be a great improvement !
