### ISSUE TITLE
Formatting y-axis?

### ISSUE THREAD

**Issue by ignacio82** [rstudio/dygraphs#80]
Is it possible to have a comma to separate thousands in y1 and format y2 as percentage? For example:

    qxts <-
      structure(
        c(
          51833, 40696, 32400, 35300, 48727, 51307, 78659,
          59919, 74599, 81119, 59096, 93196, 22.7538440761677, 24.0171024179281,
          23.7037037037037, 25.0198300283286, 24.760399778357, 25.6202857309919,
          27.4386910588744, 25.0755186167993, 26.3582621750962, 30.0225594496974,
          33.2374441586571, 31.2373921627538
        ), .Dim = c(12L, 2L), .Dimnames = list(NULL, c("number", "percentage")), index = structure(
          c(
            1396310400,
            1398902400, 1401580800, 1404172800, 1406851200, 1409529600, 1412121600,
            1414800000, 1417392000, 1420070400, 1422748800, 1425168000
          ), tzone = "", tclass = "yearmon"
        ), class = c("xts",
                     "zoo"), .indexCLASS = "yearmon", tclass = "yearmon", .indexTZ = "", tzone = ""
      )
    
    dygraph(qxts) %>%
      dyAxis("y", label = "Number") %>%
      dyAxis("y2", label = "percentage", independentTicks = TRUE) %>%
      dySeries("percentage", axis = 'y2')

Thanks!

**Comment by timelyportfolio** [comment]
`axisLabelFormatter` and `valueFormatter` provide control over the formatting.

```
dygraph(qxts) %>%
  dyAxis("y", label = "Number") %>%
  dyAxis(
    "y2",
    label = "percentage",
    independentTicks = TRUE,
    valueFormatter = 'function(d){return Math.round(d*100)/1e2 + "%"}',
    axisLabelFormatter = 'function(d){return Math.round(d*100)/1e2 + "%"}'
  ) %>%
  dySeries("percentage", axis = 'y2')
```

**Comment by ignacio82** [comment]
Looks great! Is there a way to fix the y axis label 'Number'? Right now the N is overlapping with 60,000

**Comment by timelyportfolio** [comment]
I would strongly suggest consulting the very thorough http://dygraphs.com/options.html for the full set of options.  Here, you could reduce the font size or increase the axis label width.

```
dygraph(qxts) %>%
  dyAxis(
    "y",
    label = "Number",
    #http://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript
    valueFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
    axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
    axisLabelFontSize = 10,
    axisLabelWidth = 70
  ) %>%
  dyAxis(
    "y2",
    label = "percentage",
    independentTicks = TRUE,
    valueFormatter = 'function(d){return Math.round(d*100)/1e2 + "%"}',
    axisLabelFormatter = 'function(d){return Math.round(d*100)/1e2 + "%"}'
  ) %>%
  dySeries("percentage", axis = 'y2')
```

**Comment by ignacio82** [comment]
Thanks @timelyportfolio !
