### ISSUE TITLE
Feature request: log scale x axis

### ISSUE THREAD

**Issue by bbTomas** [rstudio/dygraphs#92]
It would be great if you could integrate a log scale feature for numeric x axis like in this example
http://dygraphs.com/tests/logscale.html

In dygraphs, it is
axes : { x : {  logscale : true } }

What do you think, @dgromer?
Thank you.

**Comment by jjallaire** [comment]
Done (see https://github.com/rstudio/dygraphs/pull/93)

**Comment by bbTomas** [comment]
Thank you a lot. It works perfectly.
