### ISSUE TITLE
dygraphs not appearing in reveal.js presentations

### ISSUE THREAD

**Issue by ismayc** [rstudio/dygraphs#98]
I'm attempting to load a dygraph plot into a reveal.js presentation I wrote using RMarkdown.  When I try to publish to RPubs the dygraph is no longer visible.  It also does not appear when I Open in Browser after knitting the presentation together.  It is off and on whether it appears in the Preview after Knitting.

The exact same code does produce a dygraph in an R Markdown HTML file that I uploaded to RPubs [here](http://rpubs.com/cismay/144456).

**Comment by jjallaire** [comment]
I'm not able to reproduce this with the latest versions of rmarkdown and
dygraphs. Here's the code I'm using:

https://gist.githubusercontent.com/jjallaire/b4dead8dc4bd1cfc7b89/raw/dce86f68e0c91e0bc74901f62f2a1e6d95b0b514/reveal-dygraph.Rmd

Could you post a complete example along with sessionInfo indicating
platform and versions of installed packages.

**Comment by ismayc** [comment]
I should have the most up-to-date versions of rmarkdown and dygraphs.

The Rmd is [here](https://github.com/ismayc/Reed_WoRkshops/tree/master/Paideia_interactive_dataviz_2016/slides) and the resulting Rpub presentation is [here](http://rpubs.com/cismay/paideia_2k16_idv).  My sessionInfo is below.

```
## R version 3.2.3 (2015-12-10)
## Platform: x86_64-apple-darwin13.4.0 (64-bit)
## Running under: OS X 10.11.2 (El Capitan)
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] DT_0.1                  googleVis_0.5.10        maps_3.0.2              xts_0.9-7              
##  [5] zoo_1.7-12              readr_0.2.2             knitr_1.12              dplyr_0.4.3            
##  [9] dygraphs_0.6            pnwflights14_0.1.0.9000 plotly_2.3.0            ggplot2_2.0.0          
## [13] revealjs_0.5           
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.3        RColorBrewer_1.1-2 formatR_1.2.1      plyr_1.8.3         base64enc_0.1-3   
##  [6] viridis_0.3.2      tools_3.2.3        digest_0.6.9       jsonlite_0.9.19    evaluate_0.8      
## [11] gtable_0.1.2       lattice_0.20-33    DBI_0.3.1          yaml_2.1.13        parallel_3.2.3    
## [16] gridExtra_2.0.0    httr_1.0.0         stringr_1.0.0      htmlwidgets_0.5    grid_3.2.3        
## [21] R6_2.1.1           rmarkdown_0.9.5    RJSONIO_1.3-0      magrittr_1.5       scales_0.3.0      
## [26] htmltools_0.3      assertthat_0.1     colorspace_1.2-6   labeling_0.3       stringi_1.0-1     
## [31] lazyeval_0.1.10    munsell_0.4.2
```

**Comment by ismayc** [comment]
I've created a stripped down version to just include a ggplot2 and dygraph example.  It's called `slides_temp.Rmd` in the folder.

**Comment by jjallaire** [comment]
Thanks, I figured out the issue. You'll need to update both revealjs and
dygraphs from GitHub to get these two commits:

https://github.com/jjallaire/revealjs/commit/a4854c017eac44d969a216103551c21d66329a74

https://github.com/rstudio/dygraphs/commit/778acdaeb91b754412d928ea824632bceae3078b

**Comment by ismayc** [comment]
That fixed it.  Thanks!  

I haven't tried to put interactive plots into a presentation like this before.  I'm not sure if this is the right spot for this, but I've noticed that the cursor often doesn't match up with the values displayed with hover in these presentations.  I'm not sure how to discuss this error in a reproducible way.  I've only had issues when hovering over interactive plots in ioslides/revealjs_presentation's and not in HTML files obtained via Knit HTML.

**Comment by ismayc** [comment]
Actually, I spoke too soon.  When I tried to add a `dyRangeSelector` to the `dygraph` it resulted in the attached picture when I Open in Browser. 
![screen shot 2016-01-20 at 9 40 55 pm](https://cloud.githubusercontent.com/assets/9215614/12472592/d1b227c6-bfbe-11e5-89e0-865c67fea6d0.png)

It displays correctly in the Preview after Knitting and is interactive there.

![screen shot 2016-01-20 at 9 43 56 pm](https://cloud.githubusercontent.com/assets/9215614/12472603/efee7956-bfbe-11e5-80ea-7328701edd97.png)

**Comment by jjallaire** [comment]
Hmmm...I can't repro that (it shows up when I do Open in Browser). What
browser are you using? (I tried it with Chrome on OS X)

**Comment by ismayc** [comment]
Sorry.  That was a false alarm.  It appears now.

**Comment by hherrada** [comment]
Hi JJ, I'm checking your example on github but it is not currently rendering in my pc. Could you please confirm this is still rendering correctly in your computer? Thanks!

**Comment by jjallaire** [comment]
Yes, everything works fine for me locally. dygraphs is downloaded several
hundred times a day and we have no bug reports like this so there must be
something differnet about your environment. Be sure you have updated to the
latest versions of dygraphs, htmlwidgets, and revealjs.
